DROP DATABASE IF EXISTS prueba_catalogo;
CREATE DATABASE prueba_catalogo;
USE prueba_catalogo;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    LOCALIDAD VARCHAR(50)
);

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT PRIMARY KEY,
    RAZON_SOCIAL VARCHAR(80),
    LOCALIDAD VARCHAR(50)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE VARCHAR(60),
    PRECIO DECIMAL(10,2),
    STOCK INT,
    CATEGORIA VARCHAR(30)
);

CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

CREATE INDEX IDX_PRODUCTOS_NOMBRE ON PRODUCTOS(NOMBRE);
CREATE INDEX IDX_CLIENTES_LOCALIDAD ON CLIENTES(LOCALIDAD);

-- =============================================
-- Ejercicios
-- =============================================

-- 1) ¿Cuáles tablas contienen la columna LOCALIDAD?
SELECT TABLE_NAME AS TABLA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'prueba_catalogo'
  AND COLUMN_NAME = 'LOCALIDAD';

-- 2) ¿Cuántas columnas tiene la tabla PRODUCTOS?
SELECT COUNT(*) AS CANTIDAD_COLUMNAS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'prueba_catalogo'
  AND TABLE_NAME = 'PRODUCTOS';

-- 3) Lista de usuarios dueños de tablas + cantidad de tablas
SELECT CURRENT_USER() AS USUARIO,
       COUNT(*) AS CANTIDAD_TABLAS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'prueba_catalogo'
  AND TABLE_TYPE = 'BASE TABLE';

-- 4) Nombres de todas las tablas que tienen por lo menos un índice
SELECT DISTINCT TABLE_NAME AS TABLA
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = 'prueba_catalogo'
ORDER BY TABLE_NAME;